// <auto-generated />
using System;
using FootNotes.Annotations.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FootNotes.Annotations.Data.Migrations
{
    [DbContext(typeof(AnnotationsContext))]
    [Migration("20251109135414_InitialAnnotation")]
    partial class InitialAnnotation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FootNotes.Annotations.Domain.AnnotationSessionModels.Annotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnnotationSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("annotation_session_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("Minute")
                        .HasColumnType("integer")
                        .HasColumnName("minute");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_stamp");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AnnotationSessionId");

                    b.ToTable("annotations", (string)null);
                });

            modelBuilder.Entity("FootNotes.Annotations.Domain.AnnotationSessionModels.AnnotationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Ended")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<DateTime>("Started")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("annotation_sessions", (string)null);
                });

            modelBuilder.Entity("FootNotes.Annotations.Domain.AnnotationSessionModels.AnnotationTag", b =>
                {
                    b.Property<Guid>("AnnotationId")
                        .HasColumnType("uuid")
                        .HasColumnName("annotation_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("AnnotationId", "TagId");

                    b.ToTable("annotation_tags", (string)null);
                });

            modelBuilder.Entity("FootNotes.Annotations.Domain.TagModels.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AnnotationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AnnotationId");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("FootNotes.Annotations.Domain.AnnotationSessionModels.Annotation", b =>
                {
                    b.HasOne("FootNotes.Annotations.Domain.AnnotationSessionModels.AnnotationSession", "AnnotationSession")
                        .WithMany("Annotations")
                        .HasForeignKey("AnnotationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnnotationSession");
                });

            modelBuilder.Entity("FootNotes.Annotations.Domain.TagModels.Tag", b =>
                {
                    b.HasOne("FootNotes.Annotations.Domain.AnnotationSessionModels.Annotation", null)
                        .WithMany("Tags")
                        .HasForeignKey("AnnotationId");
                });

            modelBuilder.Entity("FootNotes.Annotations.Domain.AnnotationSessionModels.Annotation", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("FootNotes.Annotations.Domain.AnnotationSessionModels.AnnotationSession", b =>
                {
                    b.Navigation("Annotations");
                });
#pragma warning restore 612, 618
        }
    }
}
