// <auto-generated />
using System;
using FootNotes.MatchManagement.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FootNotes.MatchManagement.Data.Migrations
{
    [DbContext(typeof(MatchContext))]
    [Migration("20251116202713_InsertTeamAndMatchCode")]
    partial class InsertTeamAndMatchCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FootNotes.MatchManagement.Domain.CompetitionModels.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Scope")
                        .HasColumnType("integer")
                        .HasColumnName("scope");

                    b.Property<string>("Season")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("season");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("competitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("019a8e59-af70-731a-b307-c72c97357ca2"),
                            Name = "Premier League",
                            Scope = 3,
                            Season = "2025/2026",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("019a8e59-af70-731b-81b2-22deb795b880"),
                            Name = "Brasileirao Serie A",
                            Scope = 3,
                            Season = "2025",
                            Type = 1
                        });
                });

            modelBuilder.Entity("FootNotes.MatchManagement.Domain.MatchModels.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("AwayPenaltyScore")
                        .HasColumnType("bigint")
                        .HasColumnName("away_penalty_score");

                    b.Property<long?>("AwayScore")
                        .HasColumnType("bigint")
                        .HasColumnName("away_score");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("away_team_id");

                    b.Property<Guid?>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<byte?>("DecisionType")
                        .HasColumnType("smallint")
                        .HasColumnName("decision_type");

                    b.Property<long?>("HomePenaltyScore")
                        .HasColumnType("bigint")
                        .HasColumnName("home_penalty_score");

                    b.Property<long?>("HomeScore")
                        .HasColumnType("bigint")
                        .HasColumnName("home_score");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_team_id");

                    b.Property<string>("MatchCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("match_code");

                    b.Property<DateTime?>("MatchDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("match_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("FootNotes.MatchManagement.Domain.TeamModels.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("coach_id");

                    b.Property<bool>("HasCreatedManually")
                        .HasColumnType("boolean")
                        .HasColumnName("has_created_manually");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("short_name");

                    b.Property<string>("TeamCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("team_code");

                    b.HasKey("Id");

                    b.ToTable("teams", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
